### ISSUE TITLE
Bug: parse_float does *not work* with format 8d

### ISSUE THREAD

**Issue by mikehagerty** [LANL-Seismoacoustics/pisces#25]
You've still got an error in pisces.schema.css3.py:

tagid = Column(Integer,
               info={'default': -1, 'parse': parse_float, 'dtype': 'float', 'width': 8, 'format': '8d'})

parse_float does not work with format 8d.

Looking at css schema, this should be a number(8), so probably best to change
parse_float to parse_int and dtype to 'int'.

Also, looking at the schema, the primary key for the wftag table shouldn't even be tagid,
it should be tagname/tagid/wfid

**Comment by jkmacc-LANL** [comment]
Good catch!  I guess this table doesn't get much exercise 😉   I've made some changes in #27 that address things in both KB Core and CSS3 schema.  Feel free to review them if you've got any comments.
