### ISSUE TITLE
import obspy.taup error in util.py

### ISSUE THREAD

**Issue by jessicabobeck** [LANL-Seismoacoustics/pisces#28]
While I know python 2 is not support in the newest version, however I was hoping you could fix a minor bug in pisces 0.2.4, since my teams current project is using 2.7 still.

In `obspy 1.1.0` the taup module has been updated
on line 24 of `util.py` please change:
`from obspy.taup import taup`
to
`from obspy import taup`

**Comment by jkmacc-LANL** [comment]
Hi @jessicabobeck .  I'm happy to fix this, though I'm less clear how to fix it in this repo.  Would you like me to just push a bugfix to Pisces on PyPI?

**Comment by jessicabobeck** [comment]
Hi @jkmacc-LANL , if you could just push it to PyPI that would be great!

**Comment by jkmacc-LANL** [comment]
Unfortunately, I don't think I'll have much time to backport fixes to Python 2.7.  If you're interested in offering a PR to do this, I can certainly answer any questions that can help you through it.  Closing for now.
