### ISSUE TITLE
problem with importing pisces on Windows 

### ISSUE THREAD

**Issue by SpacelySpaceSprockets** [LANL-Seismoacoustics/pisces#29]
Having an issue with pisces on Windows.  It seems to install fine via pip, but when I start python and try to import pisces, I get a error message and a pretty strange trace dump

The error is 

> C:\Users\...\lib\libecompression.cp36-win_amd64.pyd is either not designed to run on Windows or it contains an error. Try installing the program again using the original installation media or contact your system administrator or the software vendor for support. Error status 0xc0000020.

The trace dump is

> In [2]: import pisces
[1;31m---------------------------------------------------------------------------[0m
[1;31mOSError[0m                                   Traceback (most recent call last)
[1;32m<ipython-input-2-46ea4422578a>[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [1;32mimport[0m [0mpisces[0m[1;33m[0m[0m
[0m
[1;32m~\AppData\Local\Continuum\Anaconda3\envs\python3\lib\site-packages\pisces\__init__.py[0m in [0;36m<module>[1;34m[0m
[0;32m     22[0m [1;32mfrom[0m [0mpisces[0m[1;33m.[0m[0mutil[0m [1;32mimport[0m [0mdb_connect[0m[1;33m,[0m [0mget_tables[0m[1;33m,[0m [0mtravel_times[0m[1;33m,[0m [0mmake_table[0m[1;33m[0m[0m
[0;32m     23[0m [1;32mfrom[0m [0mpisces[0m[1;33m.[0m[0mschema[0m[1;33m.[0m[0mutil[0m [1;32mimport[0m [0mstring_formatter[0m[1;33m[0m[0m
[1;32m---> 24[1;33m [1;32mfrom[0m [0mpisces[0m[1;33m.[0m[0mio[0m[1;33m.[0m[0mtrace[0m [1;32mimport[0m [0mwfdisc2trace[0m[1;33m[0m[0m
[0m[0;32m     25[0m [1;32mfrom[0m [0mpisces[0m[1;33m.[0m[0mschema[0m [1;32mimport[0m [0mkbcore[0m[1;33m[0m[0m
[0;32m     26[0m [1;32mfrom[0m [0mpisces[0m[1;33m.[0m[0mio[0m[1;33m.[0m[0mreadwaveform[0m [1;32mimport[0m [0mread_waveform[0m[1;33m[0m[0m

>[1;32m~\AppData\Local\Continuum\Anaconda3\envs\python3\lib\site-packages\pisces\io\trace.py[0m in [0;36m<module>[1;34m[0m
[0;32m      5[0m [1;32mimport[0m [0mos[0m[1;33m[0m[0m
[0;32m      6[0m [1;32mfrom[0m [0mobspy[0m[1;33m.[0m[0mcore[0m [1;32mimport[0m [0mUTCDateTime[0m[1;33m,[0m [0mTrace[0m[1;33m,[0m [0mStats[0m[1;33m[0m[0m
[1;32m----> 7[1;33m [1;32mfrom[0m [0mpisces[0m[1;33m.[0m[0mio[0m[1;33m.[0m[0mreadwaveform[0m [1;32mimport[0m [0mread_waveform[0m[1;33m[0m[0m
[0m[0;32m      8[0m [1;32mfrom[0m [0mpisces[0m[1;33m.[0m[0mio[0m[1;33m.[0m[0mutil[0m [1;32mimport[0m [0m_buildhdr[0m[1;33m[0m[0m
[0;32m      9[0m [1;33m[0m[0m

>[1;32m~\AppData\Local\Continuum\Anaconda3\envs\python3\lib\site-packages\pisces\io\readwaveform.py[0m in [0;36m<module>[1;34m[0m
[0;32m     17[0m [1;31m# C libraries[0m[1;33m[0m[1;33m[0m[0m
[0;32m     18[0m [0mext[0m[1;33m,[0m [1;33m=[0m [0msysconfig[0m[1;33m.[0m[0mget_config_vars[0m[1;33m([0m[1;34m'SO'[0m[1;33m)[0m[1;33m[0m[0m
[1;32m---> 19[1;33m [0mlibecomp[0m [1;33m=[0m [0mC[0m[1;33m.[0m[0mCDLL[0m[1;33m([0m[0mos[0m[1;33m.[0m[0mpath[0m[1;33m.[0m[0mdirname[0m[1;33m([0m[0m__file__[0m[1;33m)[0m [1;33m+[0m [0mos[0m[1;33m.[0m[0mpath[0m[1;33m.[0m[0msep[0m [1;33m+[0m [1;34m'lib'[0m [1;33m+[0m [0mos[0m[1;33m.[0m[0mpath[0m[1;33m.[0m[0msep[0m [1;33m+[0m [1;34m'libecompression'[0m [1;33m+[0m [0mext[0m[1;33m)[0m[1;33m[0m[0m
[0m[0;32m     20[0m [0mlibconvert[0m [1;33m=[0m [0mC[0m[1;33m.[0m[0mCDLL[0m[1;33m([0m[0mos[0m[1;33m.[0m[0mpath[0m[1;33m.[0m[0mdirname[0m[1;33m([0m[0m__file__[0m[1;33m)[0m [1;33m+[0m [0mos[0m[1;33m.[0m[0mpath[0m[1;33m.[0m[0msep[0m [1;33m+[0m [1;34m'lib'[0m [1;33m+[0m [0mos[0m[1;33m.[0m[0mpath[0m[1;33m.[0m[0msep[0m [1;33m+[0m [1;34m'libconvert'[0m [1;33m+[0m [0mext[0m[1;33m)[0m[1;33m[0m[0m
[0;32m     21[0m [1;33m[0m[0m

>[1;32m~\AppData\Local\Continuum\Anaconda3\envs\python3\lib\ctypes\__init__.py[0m in [0;36m__init__[1;34m(self, name, mode, handle, use_errno, use_last_error)[0m
[0;32m    346[0m [1;33m[0m[0m
[0;32m    347[0m         [1;32mif[0m [0mhandle[0m [1;32mis[0m [1;32mNone[0m[1;33m:[0m[1;33m[0m[0m
[1;32m--> 348[1;33m             [0mself[0m[1;33m.[0m[0m_handle[0m [1;33m=[0m [0m_dlopen[0m[1;33m([0m[0mself[0m[1;33m.[0m[0m_name[0m[1;33m,[0m [0mmode[0m[1;33m)[0m[1;33m[0m[0m
[0m[0;32m    349[0m         [1;32melse[0m[1;33m:[0m[1;33m[0m[0m
[0;32m    350[0m             [0mself[0m[1;33m.[0m[0m_handle[0m [1;33m=[0m [0mhandle[0m[1;33m[0m[0m

>[1;31mOSError[0m: [WinError 193] %1 is not a valid Win32 application

This is on a Windows 10 machine with Python 3.6.6  and VisualC++ 2015 Redistributable (x86) 14.0.24210

I installed it with a simple `pip install .` in the base directory.

Any ideas?

 
@mitchburnett 
@jkmacc-LANL

**Comment by jkmacc-LANL** [comment]
@SpacelySpaceSprockets I'm sorry for the long delay in responding.  I definitely don't have great insight into Windows C compilers, but we have a PR coming up that makes all C modules in Pisces *optional*.  Specifically, if you don't have data in `e1` format, than you shouldn't need any C compilers on your system.  I'll link the the PR here once it's prepared.

**Comment by jkmacc-LANL** [comment]
Version 0.3.2 is now on PyPI.  The e1 and s3 C bits are removed.  Please give it a try on Windows!
