### ISSUE TITLE
Error with sqlalchemy 1.4

### ISSUE THREAD

**Issue by jwebster-LANL** [LANL-Seismoacoustics/pisces#38]
Looks like there's an error when importing a new install of pisces.  The newest version of sql-alchemy doesn't seem to have the sqlalchemy.ext.declarative.api module anymore

> Traceback (most recent call last):
>   File "/Users/jwebster/opt/anaconda3/envs/infrapy_env/lib/python3.6/site-packages/pisces/schema/util.py", line 9, in <module>
>     from sqlalchemy.ext.declarative.api import _declarative_constructor
> ModuleNotFoundError: No module named 'sqlalchemy.ext.declarative.api'
> 
> During handling of the above exception, another exception occurred:
> ...
>     import pisces as ps
>   File "/Users/jwebster/opt/anaconda3/envs/infrapy_env/lib/python3.6/site-packages/pisces/__init__.py", line 22, in <module>
>     from pisces.util import db_connect, get_tables, travel_times, make_table
>   File "/Users/jwebster/opt/anaconda3/envs/infrapy_env/lib/python3.6/site-packages/pisces/util.py", line 26, in <module>
>     from pisces.schema.util import PiscesMeta
>   File "/Users/jwebster/opt/anaconda3/envs/infrapy_env/lib/python3.6/site-packages/pisces/schema/util.py", line 12, in <module>
>     from sqlalchemy.ext.declarative import _declarative_constructor
> ImportError: cannot import name '_declarative_constructor'

**Comment by jkmacc-LANL** [comment]
It looks like SQLA 1.4 is a [bridge version between 1.3 and 2.0](https://docs.sqlalchemy.org/en/14/changelog/migration_20.html), and has moved some things around.  `sqlalchemy <= 1.3.24` might work.

**Comment by byoung4** [comment]
> It looks like SQLA 1.4 is a [bridge version between 1.3 and 2.0](https://docs.sqlalchemy.org/en/14/changelog/migration_20.html), and has moved some things around. `sqlalchemy <= 1.3.24` might work.

I can confirm that sqlalchemy 1.3.24 works.

With a fresh installation of [miniconda](https://docs.conda.io/en/latest/miniconda.html) w/Python 3.8, the following is successful

```console
$ conda config --add channels conda-forge
$ conda config --set channel_priority strict
$ conda update -n base -c defaults conda
$ conda create -n pisces python=3.8
$ conda activate pisces
$ pip install pisces sqlalchemy==1.3.24
$ python
>>> import pisces
```

**Comment by jwebster-LANL** [comment]
not to be a pest, but will pisces' aversion to sqlalchemy=1.4 be fixed anytime soon?  A lot of packages are trying to install/upgrade to 1.4 these days, and forcing 1.3.24 is getting to be a bit of work.

**Comment by samuelchodur** [comment]
I am having trouble understanding why this [else block](https://github.com/LANL-Seismoacoustics/pisces/blob/1545db9d8cb2f56ac77dc786909cbfcdd9e0bba4/pisces/schema/util.py#L178) is necessary. Without it, all tests pass. The only way I was able to have that invoked was by doing something like this:
```
import pisces.schema.css3 as css
css.Wfdisc()
```
but that doesn't even work with the current master branch. The current master branch produces the following error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [2], in <cell line: 1>()
----> 1 css.Wfdisc()

File ~/test_projects/pisces/pisces/schema/util.py:182, in _init(self, *args, **kwargs)
    178 else:
    179     # keyword value instantiation
    180     # use SQLA's keyword constructor, then replace None attribute values with defaults
    181     _declarative_constructor(self, **kwargs)
--> 182     for c, ival in [(col, getattr(self, self._attrname[col.name], None)) for col in self.__table__.columns]:
    183         dflt = c.info.get('default', None)
    184         if ival is None:

AttributeError: 'Wfdisc' object has no attribute '__table__'
```

**Comment by jwebster-LANL** [comment]
Seriously though... what would it take to get pisces to play nice with sqlalchemy 1.4?  2.0 appears to be in beta...
