### ISSUE TITLE
Problem with contribution instructions using conda caused by channel flag

### ISSUE THREAD

**Issue by samuelchodur** [LANL-Seismoacoustics/pisces#43]
I am having a problem with following the contribution instructions using conda. [`CONTRIBUTING.md:44`](https://github.com/LANL-Seismoacoustics/pisces/blob/1545db9d8cb2f56ac77dc786909cbfcdd9e0bba4/CONTRIBUTING.md?plain=1#L44) instructs to create a new conda environment using the following command:
` $ conda create -n pisces -c obspy obspy lxml Click`

This leads to conda 'solving environment' for an extended period of time (not sure if it will ever finish). The current [Obspy install instructions](https://github.com/obspy/obspy/wiki/Installation-via-Anaconda) state to install Obspy from the conda-forge channel. Based on this, I believe Pisces instructions should be changed to the following:
`conda create -n pisces -c conda-forge obspy lxml Click`

I wanted to confirm this solution works for others because I currently have conda-forge at the top of my priority list for conda, and I am not sure if these instructions will work for the default installation without any other steps being necessary. If it does work, I can submit a pull request with the change.

**Comment by jkmacc-LANL** [comment]
@samuelchodur Sorry, `CONTRIBUTING.md` is definitely out of date.  Thank you for fixing the syntax.  Would you be willing to make a PR to change that in the file?

**Comment by samuelchodur** [comment]
Yes, I am willing! Will get that PR to you soon.
