### ISSUE TITLE
Error with reading in s3-formatted waveform data

### ISSUE THREAD

**Issue by jsakamo** [LANL-Seismoacoustics/pisces#46]
We are trying to read in older data from the IMS that is in s3 (3-byte interger) format. Pisces tries to read the data but produces the error in read_waveform:
data, flag = read_s3(DATAFILE, BYTEOFFSET, NUM)
ValueError: too many values to unpack (expected 2)

**Comment by jkmacc-LANL** [comment]
Hi @jsakamo !  Thanks for finding this bug.  It looks like the return signature of the underlying [s3 reader](https://github.com/LANL-Seismoacoustics/pisces/blob/master/pisces/io/readwaveform.py#L145) changed when it was made into pure Python, but this wasn't updated [everywhere](https://github.com/LANL-Seismoacoustics/pisces/blob/master/pisces/io/readwaveform.py#L87) in the code base.  I'm sorry for that.  If I make a quick update in `master` here, are you able to re-install pisces using the updated branch?

**Comment by jkmacc-LANL** [comment]
Alternately, you can edit your [this line](https://github.com/LANL-Seismoacoustics/pisces/blob/master/pisces/io/readwaveform.py#L87) to remove the `flag` parameter in your own installation, while this bug fix makes its way to a release on PyPI.

**Comment by jsakamo** [comment]
Hi Jon,
The alternate method, i.e., removing the flag parameter, worked successfully -- readwaveform.py is smoothly reading s3 data!

**Comment by jkmacc-LANL** [comment]
Thanks for the update, @jsakamo !  I'll still initiate the PR, and leave this open until it's done.

**Comment by jsakamo** [comment]
Would you be able to make this fix in your latest version, i.e., removing the 'flag' parameter? I'm using pisces as a dependency in my software package, so having the fix avoids the user having to manually do it. Thank you!
