### ISSUE TITLE
ps.request.get_wfdisc_rows does not accept wildcards

### ISSUE THREAD

**Issue by jwebster-LANL** [LANL-Seismoacoustics/pisces#47]
`get_wfdisc_rows( session, Wfdisc, sta='I60H1', ...)`
returns data

but
`get_wfdisc_rows(session, Wfdisc, sta='I60H%', ... )`
does not

should use:
`q.filter(wfdisc.sta.like(sta))`  instead of `wfdisc.sta == sta`

**Comment by jkmacc-LANL** [comment]
I just saw that SQLAlchemy>=1.4 supports a new [`regexp_match`](https://docs.sqlalchemy.org/en/14/core/sqlelement.html#sqlalchemy.sql.expression.ColumnOperators.regexp_match) column filter that could help with this!  

ping: @cnlg-lanl

**Comment by cnlg-lanl** [comment]
Just added wildcard support for string inputs in request.py functions
