### ISSUE TITLE
ps.db_connect with wallets

### ISSUE THREAD

**Issue by aileen-fisher** [LANL-Seismoacoustics/pisces#54]
Trying to get Pisces to connect using wallets.  The following works with SQLAlchemy v2:

```python
from sqlalchemy import create_engine
from sqlalchemy import text

cstr='oracle+cx_oracle://:@global_ro@xxxdb.xxxxxx'
print(cstr)
engine = create_engine(
        cstr,
        echo=True
        )
s='select * from CAT'
conn = engine.connect()
result = conn.execute(text(s))
for row in result:
    print (row)
```

Can you recommend how to use this with Pisces?  I'm not having luck.

EDIT: formatted the code block

**Comment by aileen-fisher** [comment]
Thanks! I'm new to python so bear with me, but we have a tool that uses Pisces to connect with a username and password:
session = ps.db_connect(conn='oracle+cx_oracle:' + '//' + db_vals['db_pwd'])
where db_pwd for us is equal to user:password@xxxdb.xxxxxx in a par file, and the os.environ variable for tns_admin path is modified to get around the wallets.  For security reasons, we are not allowed to explicitly list the password in a file, and must use wallets. 

I've tried simply replacing with:
session = ps.db_connect(conn='oracle+cx_oracle://:@global_ro@xxxdb.xxxxxx')
but I seem to get some odd empty library error with this specific tool I can't seem to make sense of, and so am wondering if it just won't connect.

I don't have a great error to show since I'm not yet very familiar with Pisces.. so actually, if you could provide a simple test script that prints validation of the session, I would be grateful.  I've tried a couple of my own that haven't yielded results, and I'd rather use a script I know is valid.

**Comment by samuelchodur** [comment]
> Hi, @aileen-fisher ! I'm happy to help, but OTOH, I'm not sure where to start looking into with this. Can you post some version of the error you're getting?

I don't use `pisces.db_connect`, but I can successfully return an sqlalchemy Session using wallets. This code is a little old, but can provide an update next week. Please ignore the sqlite bits. Also, I don't think I have tested this code with `sqlalchemy>=2.0`. 

This might help get things started for someone else. My apologies for not having a source on why it must be structured this way. I wrote this a few years ago. If I have time this weekend I can try to make a PR.

```
import sqlalchemy as sa
from sqlalchemy.orm import Session
import cx_Oracle

# Default Database
DB_STR = 'database_ro@database.db'


def get_session(db=None, sqlite=True):
    """
    returns an sqlalchemy database session
    """
    global DB_STR
    
    if db:
        DB_STR = db
    
    if sqlite:
        print(f'DB_STR variable set to: {DB_STR}')
        e = sa.create_engine(f'sqlite:///{DB_STR}')
    else:
        '''SAWarning: Oracle version (18, 14, 0, 0, 0) is known to have a  
            maximum identifier length of 128'''
        e = sa.create_engine('oracle+cx_oracle://', creator=_creator, 
                max_identifier_length=128)
    
    return Session(e)


def _creator():
    """
    returns a cx_Oracle connection that works with Oracle Wallets
    """
    c = cx_Oracle.connect(dsn=DB_STR, encoding='UTF-8')

    return c
```

**Comment by jkmacc-LANL** [comment]
@aileen-fisher, I'm not able to test, so may not be a ton of help.  The most succinct info I could find is [here](https://stackoverflow.com/a/63251821/745557), which tells you how to connect when you have everything set up properly using `cx_Oracle` directly.  This helpful b/c it tells us what connection keywords are needed, assuming config files like `tnsnames.ora` and `sqlnet.ora` are set up correctly.  In looking at the [cx_Oracle docs ](https://cx-oracle.readthedocs.io/en/latest/user_guide/initialization.html#optional-oracle-net-configuration-files), it looks like these files might be in a directory you can point to using the `TNS_ADMIN` environmental variable, which `cx_Oracle` might pick up at runtime.  Alternately, [this user](https://stackoverflow.com/a/67118000/745557) found and copied theirs into their home directory, and set their `TNS_ADMIN` environmental to point to their copied files.  

Finally, if you already have and `engine`, like you described above, you can just:

```python
from sqlalchemy.orm import Session
session = Session(engine)
```

...and you can just use that `session` like the one Pisces gives you.

@samuelchodur This is great, thank you!  Given that you're simply giving the `dsn` and `encoding` keywords to the `cx_Oracle` connection, do you think it'd also work with this?:

```python
e = sa.create_engine('oracle+cx_oracle://', 
    connect_args={
        'dsn': DB_STR,
        'encoding': 'UTF-8'
    }, 
    max_identifier_length=128)
session = Session(e)
```

**Comment by jkmacc-LANL** [comment]
Aileen, the `Session` you get back from `db_connect` _is_ a SQLAlchemy session bound to an engine just like you showed above, so it should work the same way.  Looking at your table definitions, you may not need to use `base` (depending where you got it) in your class definition.  `css.Origin` has its own `Base` that does some Pisces meta-magic, so that you can just:

```python
class Origin(css.Origin):
    ...other stuff
```

**Comment by aileen-fisher** [comment]
Great, thanks!  I think I can confirm we are hitting the db (with our standard wallets setup, SQLAlchemy 2.0.9, Pisces 0.4.0) by using the following format:

session = ps.db_connect(conn='oracle+cx_oracle://:@global_ro@xxxdb.xxxxxx')

The error I'm getting now from the tool is confusing, but most likely not related to Pisces.  Thank you very much for your help.  I plan on tracking these discoveries in our soon-to-be GitLab.

**Comment by jkmacc-LANL** [comment]
>  soon-to-be GitLab
❤️

Thank you for moving forward on it.  We can't wait!

**Comment by jkmacc-LANL** [comment]
Closing for now.

**Comment by samuelchodur** [comment]
> @samuelchodur This is great, thank you! Given that you're simply giving the `dsn` and `encoding` keywords to the `cx_Oracle` connection, do you think it'd also work with this?:
> 
> ```python
> e = sa.create_engine('oracle+cx_oracle://', 
>     connect_args={
>         'dsn': DB_STR,
>         'encoding': 'UTF-8'
>     }, 
>     max_identifier_length=128)
> session = Session(e)
> ```
Finally got a chance to test this today and it worked as expected. Much cleaner--thanks for the tip!
